title: Data and Digital Scholarship Workshop Series (Fall 2026)
description: Landing page for Hamilton Library Fall Workshop Series
theme: just-the-docs

url: https://cndhsi.github.io/fallworkshop-26

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
